config/routes.rb
Dcx::Application.routes.draw do
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/about"
  get "users/new"

  resources :orgs

  resources :users

  resources :outcomes

  resources :results

  resources :targets

  resources :campaigns

  resources :calls

  resources :constituents

end

app/models/target.rb
class Target < ActiveRecord::Base
	belongs_to :campaign
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  # GET /targets
  # GET /targets.xml
  def index
    @targets = Target.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @targets }
    end
  end

  # GET /targets/1
  # GET /targets/1.xml
  def show
    @target = Target.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/new
  # GET /targets/new.xml
  def new
    @target = Target.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/1/edit
  def edit
    @target = Target.find(params[:id])
  end

  # POST /targets
  # POST /targets.xml
  def create
    @target = Target.new(params[:target])

    respond_to do |format|
      if @target.save
        format.html { redirect_to(@target, :notice => 'Target was successfully created.') }
        format.xml  { render :xml => @target, :status => :created, :location => @target }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /targets/1
  # PUT /targets/1.xml
  def update
    @target = Target.find(params[:id])

    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to(@target, :notice => 'Target was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.xml
  def destroy
    @target = Target.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to(targets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_for(@target) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :campaign_id %><br />
    <%= f.text_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render 'form' %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<h1>Listing targets</h1>

<table>
  <tr>
    <th>Campaign</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @targets.each do |target| %>
  <tr>
    <td><%= target.campaign_id %></td>
    <td><%= target.name %></td>
    <td><%= target.description %></td>
    <td><%= link_to 'Show', target %></td>
    <td><%= link_to 'Edit', edit_target_path(target) %></td>
    <td><%= link_to 'Destroy', target, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Target', new_target_path %>

app/views/targets/new.html.erb
<h1>New target</h1>

<%= render 'form' %>

<%= link_to 'Back', targets_path %>

app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Campaign:</b>
  <%= @target.campaign_id %>
</p>

<p>
  <b>Name:</b>
  <%= @target.name %>
</p>

<p>
  <b>Description:</b>
  <%= @target.description %>
</p>


<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>