config/routes.rb
Dcx::Application.routes.draw do
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/about"
  get "users/new"

  resources :orgs

  resources :users

  resources :outcomes

  resources :results

  resources :targets

  resources :campaigns

  resources :calls

  resources :constituents

end

app/models/call.rb
class Call < ActiveRecord::Base
	has_one :campaign
	has_one :result
	
	belongs_to :constituent
	belongs_to :campaign
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.xml
  def index
    @calls = Call.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @calls }
    end
  end

  # GET /calls/1
  # GET /calls/1.xml
  def show
    @call = Call.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @call }
    end
  end

  # GET /calls/new
  # GET /calls/new.xml
  def new
    @call = Call.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
  end

  # POST /calls
  # POST /calls.xml
  def create
    @call = Call.new(params[:call])

    respond_to do |format|
      if @call.save
        format.html { redirect_to(@call, :notice => 'Call was successfully created.') }
        format.xml  { render :xml => @call, :status => :created, :location => @call }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @call.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /calls/1
  # PUT /calls/1.xml
  def update
    @call = Call.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to(@call, :notice => 'Call was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @call.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.xml
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to(calls_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :constituent_id %><br />
    <%= f.text_field :constituent_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br />
    <%= f.text_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :call_date %><br />
    <%= f.date_select :call_date %>
  </div>
  <div class="field">
    <%= f.label :call_time %><br />
    <%= f.time_select :call_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table>
  <tr>
    <th>Constituent</th>
    <th>Campaign</th>
    <th>Call date</th>
    <th>Call time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calls.each do |call| %>
  <tr>
    <td><%= call.constituent_id %></td>
    <td><%= call.campaign_id %></td>
    <td><%= call.call_date %></td>
    <td><%= call.call_time %></td>
    <td><%= link_to 'Show', call %></td>
    <td><%= link_to 'Edit', edit_call_path(call) %></td>
    <td><%= link_to 'Destroy', call, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Constituent:</b>
  <%= @call.constituent_id %>
</p>

<p>
  <b>Campaign:</b>
  <%= @call.campaign_id %>
</p>

<p>
  <b>Call date:</b>
  <%= @call.call_date %>
</p>

<p>
  <b>Call time:</b>
  <%= @call.call_time %>
</p>


<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>