config/routes.rb
Dcx::Application.routes.draw do
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/about"
  get "users/new"

  resources :orgs

  resources :users

  resources :outcomes

  resources :results

  resources :targets

  resources :campaigns

  resources :calls

  resources :constituents

end

app/models/outcome.rb
class Outcome < ActiveRecord::Base
	belongs_to :result
	validates :description, :length => { :maximum => 40 }
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  # GET /outcomes
  # GET /outcomes.xml
  def index
    @outcomes = Outcome.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @outcomes }
    end
  end

  # GET /outcomes/1
  # GET /outcomes/1.xml
  def show
    @outcome = Outcome.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @outcome }
    end
  end

  # GET /outcomes/new
  # GET /outcomes/new.xml
  def new
    @outcome = Outcome.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @outcome }
    end
  end

  # GET /outcomes/1/edit
  def edit
    @outcome = Outcome.find(params[:id])
  end

  # POST /outcomes
  # POST /outcomes.xml
  def create
    @outcome = Outcome.new(params[:outcome])

    respond_to do |format|
      if @outcome.save
        format.html { redirect_to(@outcome, :notice => 'Outcome was successfully created.') }
        format.xml  { render :xml => @outcome, :status => :created, :location => @outcome }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @outcome.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /outcomes/1
  # PUT /outcomes/1.xml
  def update
    @outcome = Outcome.find(params[:id])

    respond_to do |format|
      if @outcome.update_attributes(params[:outcome])
        format.html { redirect_to(@outcome, :notice => 'Outcome was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @outcome.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outcomes/1
  # DELETE /outcomes/1.xml
  def destroy
    @outcome = Outcome.find(params[:id])
    @outcome.destroy

    respond_to do |format|
      format.html { redirect_to(outcomes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/outcomes/_form.html.erb
<%= form_for(@outcome) do |f| %>
  <% if @outcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outcome.errors.count, "error") %> prohibited this outcome from being saved:</h2>

      <ul>
      <% @outcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :outcome_description %><br />
    <%= f.text_field :outcome_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outcomes/edit.html.erb
<h1>Editing outcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @outcome %> |
<%= link_to 'Back', outcomes_path %>

app/views/outcomes/index.html.erb
<h1>Listing outcomes</h1>

<table>
  <tr>
    <th>Outcome description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outcomes.each do |outcome| %>
  <tr>
    <td><%= outcome.outcome_description %></td>
    <td><%= link_to 'Show', outcome %></td>
    <td><%= link_to 'Edit', edit_outcome_path(outcome) %></td>
    <td><%= link_to 'Destroy', outcome, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outcome', new_outcome_path %>

app/views/outcomes/new.html.erb
<h1>New outcome</h1>

<%= render 'form' %>

<%= link_to 'Back', outcomes_path %>

app/views/outcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Outcome description:</b>
  <%= @outcome.outcome_description %>
</p>


<%= link_to 'Edit', edit_outcome_path(@outcome) %> |
<%= link_to 'Back', outcomes_path %>